import { Routes } from '../constants/routes';

export type AuthStackParamList = {
  [Routes.Welcome]: undefined;
  [Routes.Login]: undefined;
  [Routes.Register]: undefined;
  [Routes.OTP]: { phone: string };
  [Routes.RoleSelect]: undefined;
  [Routes.ProfileSetup]: undefined;
  [Routes.AIOnboarding]: undefined;
};

export type ExamStackParamList = {
  [Routes.ExamList]: undefined;
  [Routes.ExamCategories]: undefined;
  [Routes.CategorySubcategories]: { categoryKey: string; categoryTitle: string };
  [Routes.GradeSubjects]: { categoryKey: string; parentKey: string; parentTitle: string };
  [Routes.CategoryExams]: { categoryKey: string; categoryTitle: string; subKey?: string; subject?: string };
  [Routes.LiveExamsList]: undefined;
  [Routes.LiveExamDetail]: { examId: string; title?: string; startAt?: string; participants?: number };
  [Routes.MyExams]: undefined;
  [Routes.ExamPurchaseConfirm]: { examId: string; title?: string; price: number; subject?: string; questions?: number };
  [Routes.ExamPurchaseSuccess]: { examId: string; title?: string; subject?: string; questions?: number; successRate?: number };
  [Routes.ExamFilterSheet]: undefined;
  [Routes.ExamInfo]: { examId: string; title?: string };
  [Routes.SchoolExams]: undefined;
  [Routes.AIExamRecommendations]: undefined;
  [Routes.ExamBrowse]: { subject?: string; category?: string } | undefined;
  [Routes.NewExam]: {
    questionCount?: number;
    duration?: number;
    difficulty?: 'easy' | 'medium' | 'hard' | 'mixed';
    questionType?: 'test' | 'open' | 'both';
    examType?: 'practice' | 'monthly' | 'national' | 'live';
  } | undefined;
  [Routes.ExamDetail]: { examId: string; title: string };
  [Routes.ExamSession]: undefined;
  [Routes.ExamResult]: { examId?: string } | undefined;
  [Routes.ExamReview]: { examId: string; filter?: 'all' | 'wrong' | 'correct' };
  [Routes.MonthlyExamDetail]: { examId: string; title: string };
  [Routes.LiveExamWaiting]: { examId: string; title: string };
  [Routes.LiveExamSession]: undefined;
  [Routes.ExamRanking]: { examId?: string } | undefined;
  [Routes.LiveLeaderboard]: undefined;
  [Routes.CompetitionResult]: { userScore?: number; opponentScore?: number; userName?: string; opponentName?: string; mode?: 'bot' | 'live'; userCorrect?: number; opponentCorrect?: number; totalQuestions?: number; xpEarned?: number; medalsEarned?: number } | undefined;
  [Routes.DuelMatch]: { mode?: 'bot' | 'live'; opponentName?: string; opponentLevel?: number; subject?: string; questionCount?: number; prize?: number; stake?: number } | undefined;
  [Routes.DuelMode]: undefined;
  [Routes.DuelSession]: { mode?: 'bot' | 'live'; opponentName?: string; opponentLevel?: number; subject?: string; questionCount?: number; stake?: number } | undefined;
  [Routes.DuelInvite]: { challengerName?: string; challengerLevel?: number; challengerSchool?: string; challengerXp?: number; challengerWinRate?: number; subject?: string; questionCount?: number; stake?: number } | undefined;
  [Routes.DuelHistory]: undefined;
  [Routes.CertificatePreview]: { examId: string };
  [Routes.CertificateList]: undefined;
  [Routes.ExamHistory]: undefined;
  [Routes.ExamFilter]: undefined;
  [Routes.ExamSettings]: { examId?: string; title?: string } | undefined;
};

export type MarketplaceStackParamList = {
  [Routes.MarketplaceHome]: undefined;
  [Routes.AskQuestion]: undefined;
  [Routes.QuestionDetail]: { questionId: string };
  [Routes.AIAnswer]: undefined;
  [Routes.AISolution]: { question?: string; questionId?: string } | undefined;
  [Routes.AIAnswerFallback]: undefined;
  [Routes.LessonRequest]: undefined;
  [Routes.InterestedTeachers]: { requestId?: string; requestTitle?: string };
};

export type ProfileStackParamList = {
  [Routes.ProfileHome]: undefined;
  [Routes.EditProfile]: { role?: 'teacher' | 'student' | 'parent' } | undefined;
  [Routes.Dashboard]: undefined;
  [Routes.Wallet]: undefined;
  [Routes.ReferralBalance]: undefined;
  [Routes.Settings]: undefined;
  [Routes.NotificationSettings]: undefined;
  [Routes.TermsOfService]: undefined;
  [Routes.Support]: undefined;
  [Routes.HelpCenter]: undefined;
  [Routes.ReportProblem]: undefined;
  [Routes.AboutApp]: undefined;
  [Routes.ChangePassword]: undefined;
  [Routes.PasswordChanged]: undefined;
  [Routes.AccountManagement]: undefined;
  [Routes.BlockedUsers]: undefined;
  [Routes.DeactivateReason]: undefined;
  [Routes.AccountDeactivated]: undefined;
  [Routes.DeleteAccountConfirm]: undefined;
  [Routes.LogoutConfirm]: undefined;
};

export type LearningStackParamList = {
  [Routes.LearningHome]: undefined;
  [Routes.FlashcardSession]: undefined;
  [Routes.MemoryAI]: undefined;
  [Routes.LearningGroups]: undefined;
  [Routes.LearningGroupDetail]: { groupId: string; title: string; members?: number; online?: number; level?: string; isChallenge?: boolean };
  [Routes.LearningStats]: undefined;
};

export type HomeStackParamList = {
  [Routes.HomeMain]: undefined;
  [Routes.DailyMissions]: undefined;
  [Routes.AIStudyPath]: undefined;
  [Routes.SpinWheel]: undefined;
  [Routes.CoinShop]: { coins?: number; onPurchase?: (item: { id: string; price: number; title: string }) => void } | undefined;
  [Routes.Achievements]: undefined;
  [Routes.Leaderboard]: undefined;
  [Routes.LeaderboardDetail]: undefined;
  [Routes.LiveActivity]: undefined;
  [Routes.News]: undefined;
  [Routes.TodaysTasks]: undefined;
  [Routes.AIStudyPlan]: undefined;
  [Routes.MotivationReminder]: undefined;
  [Routes.LearningProgress]: undefined;
  [Routes.TopicProgress]: { topic?: string } | undefined;
  [Routes.ReviewTopics]: undefined;
  [Routes.AIPracticeBuilder]: undefined;
  [Routes.WeakTopics]: undefined;
  [Routes.Favorites]: undefined;
  [Routes.RecentlyViewed]: undefined;
  [Routes.League]: undefined;
  [Routes.SchoolRanking]: undefined;
  [Routes.SchoolSearch]: undefined;
  [Routes.SchoolDetail]: { schoolName?: string };
  [Routes.Notifications]: undefined;
  [Routes.Settings]: undefined;
  [Routes.NotificationSettings]: undefined;
  [Routes.SmartFeed]: undefined;
  [Routes.StreakProtection]: { currentStreak?: number } | undefined;
  [Routes.LanguageSelect]: undefined;
  [Routes.TwoFactor]: undefined;
  [Routes.BlockedUsers]: undefined;
  [Routes.ChangePassword]: undefined;
  [Routes.PasswordChanged]: undefined;
  [Routes.HelpCenter]: undefined;
  [Routes.Support]: undefined;
  [Routes.ReportProblem]: undefined;
  [Routes.TermsOfService]: undefined;
  [Routes.AboutApp]: undefined;
  [Routes.PaymentMethod]: undefined;
  [Routes.CardPayment]: undefined;
  [Routes.PaymentSuccess]: undefined;
  [Routes.PaymentFailed]: undefined;
  [Routes.Subscription]: undefined;
  [Routes.Plans]: undefined;
  [Routes.PlanCompare]: undefined;
  [Routes.PremiumBenefits]: undefined;
  [Routes.Subscription]: undefined;
  [Routes.SubscriptionRenew]: undefined;
  [Routes.SubscriptionCancel]: undefined;
  [Routes.Friends]: undefined;
  [Routes.AllOpenRequests]: undefined;
  [Routes.LessonRequestDetail]: { requestId: string };
  [Routes.MyRequests]: undefined;
  [Routes.AIRecommendations]: undefined;
  [Routes.Search]: undefined;
  [Routes.TeacherBadges]: undefined;
  [Routes.TeacherLevel]: undefined;
  [Routes.VerifiedTeacher]: undefined;
  [Routes.TopTeachersLeaderboard]: undefined;
  [Routes.StreakDashboard]: undefined;
  [Routes.StreakDetail]: { days?: number } | undefined;
  [Routes.StreakWarning]: undefined;
  [Routes.StreakRecovery]: undefined;
  [Routes.MissionProgress]: undefined;
  [Routes.MissionStart]: undefined;
  [Routes.PerformanceSummary]: undefined;
  [Routes.ImprovementTips]: undefined;
  [Routes.WeeklyReport]: undefined;
  [Routes.SocialHub]: undefined;
  [Routes.FindFriend]: undefined;
  [Routes.MyFriends]: undefined;
  [Routes.TeacherProfilePremium]: { teacherId?: string } | undefined;
  [Routes.FriendsLeaderboard]: undefined;
  [Routes.InviteFriends]: undefined;
};

export type AppTabParamList = {
  [Routes.Home]: undefined;
  Exams: undefined;
  Learn: undefined;
  [Routes.AIMentor]: undefined;
  Marketplace: undefined;
  [Routes.Bookmarks]: undefined;
  Chat: undefined;
  Booking: undefined;
  [Routes.Profile]: undefined;
  Calculators: undefined;
};

export type CalcStackParamList = {
  [Routes.Calculators]: undefined;
  [Routes.SemesterCalc]: undefined;
  [Routes.AnnualCalc]: undefined;
  [Routes.ScoreCalc]: undefined;
  [Routes.QualityCalc]: undefined;
  [Routes.DIMCalc]: undefined;
  [Routes.CalcHistory]: undefined;
  [Routes.CalcSaved]: undefined;
};
